language: ruby
gemfile:
  - Gemfile_rails_3
  - Gemfile_rails_4
  - Gemfile_rails_5
rvm:
  - ruby-2.1.10
  - ruby-2.2.7
  - ruby-2.3.4
  - ruby-2.4.1
  - ruby-2.5.5
  - jruby-9.1.9.0
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11  
before_script:
  - psql --version
  - psql -c 'CREATE DATABASE locker_test;' -U postgres
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
  - cp config/database.yml.travis config/database.yml
script: bundle exec rspec
matrix:
  exclude:
    - rvm: ruby-2.4.1
      gemfile: Gemfile_rails_3
services:
  - postgresql
addons:
  postgresql: "11.2"
