language: ruby
gemfile:
  - Gemfile_rails_3
  - Gemfile_rails_4
  - Gemfile_rails_5
rvm:
  - ruby-2.1.10
  - ruby-2.2.7
  - ruby-2.3.4
  - ruby-2.4.1
  - ruby-2.5.5
  - jruby-9.1.9.0
script: bundle exec rspec
matrix:
  exclude:
    - rvm: ruby-2.4.1
      gemfile: Gemfile_rails_3
services:
  - postgresql
addons:
  postgresql: "11.2"
