language: ruby
gemfile:
  - Gemfile_rails_3
  - Gemfile_rails_4
  - Gemfile_rails_5
rvm:
  - ruby-2.1.10
  - ruby-2.2.7
  - ruby-2.3.4
  - ruby-2.4.1
  - ruby-2.5.5
  - jruby-9.1.9.0
before_script:
  - psql --version
  - psql -c 'CREATE DATABASE locker_test;' -U postgres
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
script: bundle exec rspec
matrix:
  exclude:
    - rvm: ruby-2.4.1
      gemfile: Gemfile_rails_3
addons:
  postgresql: "11"
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11
